---
title: "U.S. Beer Brewery Assessment"
author: "Eric McCandless, Jordan Kassof"
date: "October 5, 2017"
output: 
  html_document:
    keep_md: TRUE
---

## Introduction

Market research about U.S. beers and breweries. Etc.

#### Question 1: Which states have the most breweries?

```{r brewery_by_state, message = FALSE, warning=FALSE, fig.align='center'}
source('./analysis/Q1_Brewery_Per_State.R')

#install.packages("choroplethr")
#install.packages("choroplethrMaps")
library(choroplethr)
map_data <- State_Counts
names(map_data) <- c("region.abb", "value")
map_data$region <- tolower(state.name[match(map_data$region.abb,state.abb)])
map_data$region[is.na(map_data$region)] <- "district of columbia"
state_choropleth(map_data,
                 title = "U.S. Distribution of Breweries",
                 legend = "Number of Breweries",
                 num_colors = 8)
knitr::kable(cbind(State_Counts[1:26, ], rbind(State_Counts[27:51, ], c("", ""))))
```


#### Question 2: Merging bBeer and brewery data.

```{r data_merge}
source('./analysis/Q2_Merge.R')
head(All_Data, 6)
tail(All_Data, 6)
```

#### Question 3: Determine the number of NAs in each column.
```{r NAs}
sapply(All_Data, function(x) sum(is.na(x)))    
```


#### Question 4: Calculate Median Alcohol Content and International Bitterness Units

```{r meds_ibv_abu, message=FALSE, warning=FALSE, fig.align='center'}
source("./analysis/Q4_Med_IBU_ABV.R")

library(ggplot2)
library(forcats)

ggplot(meds_by_state, aes(x = fct_reorder(State, ABV_Medians))) +
  geom_col(aes(y = ABV_Medians, fill = ABV_Medians)) +
  xlab("States") +
  ylab("Alcohol by Volume") +
  ggtitle("Median ABV by State") +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1),
    legend.position = 'none'
  )

ggplot(meds_by_state, aes(x = fct_reorder(State, IBU_Medians))) +
  geom_col(aes(y = IBU_Medians, fill = IBU_Medians)) +
  xlab("States") +
  ylab("International Bitterness Units") +
  ggtitle("Median Bitterness by State") +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1),
    legend.position = 'none'
  )
```


#### Question 5

#### Question 6

#### Question 7